/**
 * ReportGenerator — Generate professional pre-production reports
 * Creates elegant, printable HTML reports with scene information and screenshots
 */

export interface ReportData {
  projectName: string;
  sceneId: string;
  generatedDate: Date;
  shots: ShotInfo[];
  elements: ElementInfo[];
  screenshots: Map<string, string>;
  birdsEyeView?: string;
  metadata?: {
    totalCameras: number;
    totalLights: number;
    totalCast: number;
    totalCrew: number;
  };
}

export interface ShotInfo {
  number: number;
  cameraName: string;
  shotType: string;
  lens?: string;
  movement?: string;
  notes?: string;
  position: { x: number; y: number; z: number };
  rotation: { x: number; y: number; z: number };
  screenshot?: string;
}

export interface ElementInfo {
  type: string;
  name: string;
  position: { x: number; y: number; z: number };
  notes?: string;
}

/**
 * Generate HTML report
 */
export function generateHTMLReport(data: ReportData): string {
  const formattedDate = data.generatedDate.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.projectName} — Pre-Production Report</title>
  <style>
    ${getReportStyles()}
  </style>
</head>
<body>
  <div class="report-container">

    <!-- Cover Page -->
    <div class="report-page cover-page">
      <div class="cover-content">
        <div class="cover-badge">Shot Caller · Pre-Production</div>
        <h1 class="cover-title">${data.projectName}</h1>
        <p class="cover-subtitle">Technical Planning Report</p>
        <div class="cover-meta">
          <div class="cover-meta-item">
            <span class="cover-meta-label">Scene ID</span>
            <span class="cover-meta-value">${data.sceneId}</span>
          </div>
          <div class="cover-meta-item">
            <span class="cover-meta-label">Generated</span>
            <span class="cover-meta-value">${formattedDate}</span>
          </div>
          <div class="cover-meta-item">
            <span class="cover-meta-label">Total Shots</span>
            <span class="cover-meta-value">${data.shots.length}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Scene Overview -->
    <div class="report-page">
      <h2 class="section-title">Scene Overview</h2>

      ${data.birdsEyeView ? `
        <div class="birds-eye-section">
          <h3 class="subsection-title">Bird's Eye View</h3>
          <img src="${data.birdsEyeView}" alt="Bird's eye view" class="birds-eye-image" />
        </div>
      ` : ""}

      <div class="stats-grid">
        <div class="stat-card">
          <div class="stat-icon">🎥</div>
          <div class="stat-value">${data.metadata?.totalCameras || 0}</div>
          <div class="stat-label">Camera Positions</div>
        </div>
        <div class="stat-card">
          <div class="stat-icon">💡</div>
          <div class="stat-value">${data.metadata?.totalLights || 0}</div>
          <div class="stat-label">Lighting Setups</div>
        </div>
        <div class="stat-card">
          <div class="stat-icon">👤</div>
          <div class="stat-value">${data.metadata?.totalCast || 0}</div>
          <div class="stat-label">Cast Positions</div>
        </div>
        <div class="stat-card">
          <div class="stat-icon">🎬</div>
          <div class="stat-value">${data.metadata?.totalCrew || 0}</div>
          <div class="stat-label">Crew Positions</div>
        </div>
      </div>
    </div>

    <!-- Shot List -->
    <div class="report-page">
      <h2 class="section-title">Shot List</h2>

      ${data.shots.map((shot) => generateShotCard(shot)).join("")}
    </div>

    <!-- Equipment & Elements -->
    <div class="report-page">
      <h2 class="section-title">Equipment & Elements</h2>

      <table class="elements-table">
        <thead>
          <tr>
            <th>Type</th>
            <th>Name</th>
            <th>Position</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          ${data.elements.map((el) => `
            <tr>
              <td><span class="element-type-badge">${el.type}</span></td>
              <td>${el.name}</td>
              <td class="position-cell">
                X: ${el.position.x.toFixed(2)}<br>
                Y: ${el.position.y.toFixed(2)}<br>
                Z: ${el.position.z.toFixed(2)}
              </td>
              <td>${el.notes || "—"}</td>
            </tr>
          `).join("")}
        </tbody>
      </table>
    </div>

    <!-- Footer -->
    <div class="report-footer">
      <p>Generated by Shot Caller · Pre-Visualization Platform</p>
      <p>🤖 Powered by AI-assisted planning</p>
    </div>

  </div>

  <script>
    // Enable print functionality
    function printReport() {
      window.print();
    }

    // Add print button if not already printing
    if (!window.matchMedia('print').matches) {
      const printBtn = document.createElement('button');
      printBtn.className = 'print-button';
      printBtn.textContent = '🖨️ Print Report';
      printBtn.onclick = printReport;
      document.body.appendChild(printBtn);
    }
  </script>
</body>
</html>`;
}

function generateShotCard(shot: ShotInfo): string {
  return `
    <div class="shot-card">
      <div class="shot-header">
        <div class="shot-number">Shot ${String(shot.number).padStart(2, "0")}</div>
        <div class="shot-name">${shot.cameraName}</div>
      </div>

      ${shot.screenshot ? `
        <div class="shot-screenshot">
          <img src="${shot.screenshot}" alt="${shot.cameraName}" />
        </div>
      ` : ""}

      <div class="shot-details">
        <div class="shot-detail-grid">
          <div class="shot-detail">
            <span class="shot-detail-label">Shot Type</span>
            <span class="shot-detail-value">${shot.shotType}</span>
          </div>
          ${shot.lens ? `
            <div class="shot-detail">
              <span class="shot-detail-label">Lens</span>
              <span class="shot-detail-value">${shot.lens}</span>
            </div>
          ` : ""}
          ${shot.movement ? `
            <div class="shot-detail">
              <span class="shot-detail-label">Movement</span>
              <span class="shot-detail-value">${shot.movement}</span>
            </div>
          ` : ""}
        </div>

        <div class="shot-position">
          <span class="shot-detail-label">Camera Position</span>
          <div class="position-values">
            <span>X: ${shot.position.x.toFixed(2)}</span>
            <span>Y: ${shot.position.y.toFixed(2)}</span>
            <span>Z: ${shot.position.z.toFixed(2)}</span>
          </div>
        </div>

        ${shot.notes ? `
          <div class="shot-notes">
            <span class="shot-detail-label">Notes</span>
            <p>${shot.notes}</p>
          </div>
        ` : ""}
      </div>
    </div>
  `;
}

function getReportStyles(): string {
  return `
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'IBM Plex Sans', sans-serif;
      background: #f9fafb;
      color: #111827;
      line-height: 1.6;
    }

    .report-container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
    }

    .report-page {
      padding: 3rem;
      page-break-after: always;
    }

    /* Cover Page */
    .cover-page {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
      color: white;
      text-align: center;
    }

    .cover-badge {
      display: inline-block;
      padding: 0.5rem 1rem;
      background: rgba(251, 191, 36, 0.2);
      border: 1px solid rgba(251, 191, 36, 0.4);
      border-radius: 9999px;
      font-size: 0.875rem;
      font-weight: 500;
      color: #fbbf24;
      margin-bottom: 2rem;
    }

    .cover-title {
      font-size: 4rem;
      font-weight: 700;
      margin-bottom: 1rem;
      letter-spacing: -0.025em;
    }

    .cover-subtitle {
      font-size: 1.5rem;
      color: rgba(255, 255, 255, 0.7);
      margin-bottom: 3rem;
    }

    .cover-meta {
      display: flex;
      gap: 3rem;
      justify-content: center;
      margin-top: 3rem;
    }

    .cover-meta-item {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }

    .cover-meta-label {
      font-size: 0.875rem;
      color: rgba(255, 255, 255, 0.6);
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    .cover-meta-value {
      font-size: 1.25rem;
      font-weight: 600;
    }

    /* Section Titles */
    .section-title {
      font-size: 2rem;
      font-weight: 700;
      margin-bottom: 2rem;
      color: #0f172a;
      border-bottom: 3px solid #fbbf24;
      padding-bottom: 0.75rem;
    }

    .subsection-title {
      font-size: 1.5rem;
      font-weight: 600;
      margin-bottom: 1rem;
      color: #1e293b;
    }

    /* Stats Grid */
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 1.5rem;
      margin-bottom: 2rem;
    }

    .stat-card {
      padding: 1.5rem;
      background: #f8fafc;
      border-radius: 12px;
      text-align: center;
      border: 1px solid #e2e8f0;
    }

    .stat-icon {
      font-size: 2rem;
      margin-bottom: 0.5rem;
    }

    .stat-value {
      font-size: 2.5rem;
      font-weight: 700;
      color: #0f172a;
      margin-bottom: 0.25rem;
    }

    .stat-label {
      font-size: 0.875rem;
      color: #64748b;
    }

    /* Bird's Eye View */
    .birds-eye-section {
      margin-bottom: 2rem;
    }

    .birds-eye-image {
      width: 100%;
      border-radius: 12px;
      border: 2px solid #e2e8f0;
      margin-top: 1rem;
    }

    /* Shot Cards */
    .shot-card {
      background: #ffffff;
      border: 2px solid #e2e8f0;
      border-radius: 12px;
      overflow: hidden;
      margin-bottom: 2rem;
      page-break-inside: avoid;
    }

    .shot-header {
      display: flex;
      align-items: center;
      gap: 1rem;
      padding: 1rem 1.5rem;
      background: #f8fafc;
      border-bottom: 1px solid #e2e8f0;
    }

    .shot-number {
      font-size: 1.25rem;
      font-weight: 700;
      color: #fbbf24;
    }

    .shot-name {
      font-size: 1.125rem;
      font-weight: 600;
      color: #0f172a;
    }

    .shot-screenshot {
      width: 100%;
      aspect-ratio: 16/9;
      overflow: hidden;
      background: #000;
    }

    .shot-screenshot img {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }

    .shot-details {
      padding: 1.5rem;
    }

    .shot-detail-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 1rem;
      margin-bottom: 1rem;
    }

    .shot-detail {
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
    }

    .shot-detail-label {
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: #64748b;
    }

    .shot-detail-value {
      font-size: 1rem;
      color: #0f172a;
    }

    .shot-position {
      margin-bottom: 1rem;
    }

    .position-values {
      display: flex;
      gap: 1rem;
      margin-top: 0.5rem;
      font-family: 'IBM Plex Mono', monospace;
      font-size: 0.875rem;
      color: #475569;
    }

    .shot-notes p {
      margin-top: 0.5rem;
      color: #475569;
      font-size: 0.9375rem;
    }

    /* Elements Table */
    .elements-table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 1rem;
    }

    .elements-table thead {
      background: #f8fafc;
      border-bottom: 2px solid #e2e8f0;
    }

    .elements-table th {
      padding: 1rem;
      text-align: left;
      font-weight: 600;
      font-size: 0.875rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: #64748b;
    }

    .elements-table td {
      padding: 1rem;
      border-bottom: 1px solid #f1f5f9;
      font-size: 0.9375rem;
    }

    .element-type-badge {
      display: inline-block;
      padding: 0.25rem 0.75rem;
      background: #fef3c7;
      color: #92400e;
      border-radius: 6px;
      font-size: 0.8125rem;
      font-weight: 500;
    }

    .position-cell {
      font-family: 'IBM Plex Mono', monospace;
      font-size: 0.8125rem;
      color: #64748b;
      line-height: 1.4;
    }

    /* Footer */
    .report-footer {
      padding: 2rem 3rem;
      text-align: center;
      color: #94a3b8;
      font-size: 0.875rem;
      border-top: 1px solid #e2e8f0;
    }

    .report-footer p {
      margin: 0.25rem 0;
    }

    /* Print Button */
    .print-button {
      position: fixed;
      bottom: 2rem;
      right: 2rem;
      padding: 1rem 2rem;
      background: #0f172a;
      color: white;
      border: none;
      border-radius: 12px;
      font-size: 1rem;
      font-weight: 600;
      cursor: pointer;
      box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);
      transition: all 0.2s;
    }

    .print-button:hover {
      background: #1e293b;
      transform: translateY(-2px);
      box-shadow: 0 15px 30px rgba(0, 0, 0, 0.3);
    }

    /* Print Styles */
    @media print {
      body {
        background: white;
      }

      .print-button {
        display: none;
      }

      .report-page {
        page-break-after: always;
      }

      .shot-card {
        page-break-inside: avoid;
      }
    }
  `;
}

/**
 * Download report as HTML file
 */
export function downloadReport(html: string, filename: string): void {
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
